### ISSUE TITLE
Json not sending with the ticket

### ISSUE THREAD

**Issue by timgaunt** [ChangemakerStudios/Seq.App.YouTrack#13]
I've just spotted this error log in Seq after sending to YouTrack (the json isn't attached)

System.IO.FileNotFoundException: Could not find file 'xxx\Seq\AppData\hostedapp-4\appinstance-1154\SeqAppYouTrack-TEST-123.json'.
File name: 'xxx\Seq\AppData\hostedapp-4\appinstance-1154\SeqAppYouTrack-TEST-123.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at Seq.App.YouTrack.YouTrackIssuePoster.<OnAsync>d__6.MoveNext()

**Comment by Jaben** [comment]
Are you running Seq on Windows or inside a docker container?

**Comment by timgaunt** [comment]
Running Windows on a VM on AWS

**Comment by timgaunt** [comment]
@Jaben is there anything we can do to help get this resolved?

**Comment by nblumhardt** [comment]
@timgaunt in case you're able to take a look, I think the problem is in these two lines:

https://github.com/ChangemakerStudios/Seq.App.YouTrack/blob/661be24fdeed5e71f7bb652cf98512eebbef7b02/src/Seq.App.YouTrack/YouTrackIssuePoster.cs#L127

`GetJsonEventFile()` uses Serilog's `WriteTo.File()`:

https://github.com/ChangemakerStudios/Seq.App.YouTrack/blob/661be24fdeed5e71f7bb652cf98512eebbef7b02/src/Seq.App.YouTrack/YouTrackIssuePoster.cs#L209

Since Serilog swallows exceptions, it's likely that the file write is failing, but Serilog is chewing up the exception and stopping us from getting more details on the problem.

A quick thing to try might be to use `AuditTo.File()` instead of `WriteTo`: this will cause the exception to be thrown from Serilog. If the _Serilog.Sinks.File_ version here doesn't have auditing, hooking up `SelfLog` to the app's diagnostic logger (`Host.Logger`) should surface the info.

HTH!

**Comment by timgaunt** [comment]
Cheers @nblumhardt will take a look but will I safely be able to replace the app without having access to the nuget feed?

**Comment by nblumhardt** [comment]
Hi Tim; I think the trick will be to add a second NuGet feed based on a Windows folder location (e.g. `C:\Feed` instead of a NuGet URI. The _Settings > Feeds_ page can handle server-local paths like this.

After that, you can drop the .nupkg from the build (any version) to that feed location, and create a new instance of it that's completely separate from the existing one by using _Install from NuGet_ and selecting the local feed. Seq keeps packages from different feeds completely separate, so you can install/run/update/remove instances of the test package without disrupting the "real" instance you have installed already. Let me know if you need more info 👍

**Comment by Jaben** [comment]
The latest (2.1.18) has the Audit change suggested by @nblumhardt. Try that version and let me know the logger exception.
